# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c464982ec026107306deb2c11d2c370a3489991061f22e722ce6a4815377247f2c501d91119d82a0ecd70d753bc75021e0b2753dd9f785d1d31cbcf299d28dc

test:
  secret_key_base: 703de374287815c74ca3f02871b5e0ace383fe47dc87ad044b61a6bd5444a115c30c7d7a59a52ce5a1ac4e498ebc778de438ed36c94b5ca195bf53ad682fb7dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
